### ISSUE TITLE
Construir projeto inicial

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/practice-enquete#1]
Como este é um projeto novo, faz-se necessário alinharmos os objetivos que ele possui, quais funcionalidades deve apresentar e porque isso é importante. Portanto, peço que todos que tiverem uma visão sobre o que o Enquette deve ser, comentem aqui para que fiquemos bem alinhados quanto a o que deve ser desenvolvido. Ideias também podem ser comentadas.

**Comment by CleissonVieira** [comment]
Eu estava criando uma Issue sobre, mas como aqui vai ser a definição do inicio desse projeto vamos definir alguns passos:
- [x] Criar o repositório (não precisa de comentários)
- [x] Iniciar o projeto e estruturar as pastas (não precisa de comentários)
- [x] Definir os objetos que armazenaremos, como enquetes, perguntas e respostas (qualquer sugestão deve ser comentada nesta Issue)
- [x] Definir quais telas vão existir e qual papel cada uma vai desempenhar (necessário um comentário com as telas em forma de tópico e explicações de cada uma nessa Issue)
- [x] Issue para prototipar o layout das telas (ideias devem ser publicadas nesta Issue)

A partir do último item pode ser iniciado o desenvolvimento.

**Comment by andrewmsilva** [comment]
Com relação à arquitetura do projeto (_i.e._, estrutura de pastas e terminologia arquivos), podemos ir definindo conforme desenvolvemos. No entanto, o plano é seguirmos boas práticas de arquitetura, como criar `components`, `controllers`, `resolvers` e coisas assim.

**Comment by jeanchilger** [comment]
Em relação à padrões de código, caso não tenham nada definido tenho uma sugestão. O [Style Guide do Airbnb de JavaScript](https://github.com/airbnb/javascript) é muito bom, e tem definições para React, CSS e SASS também.

Isto é apenas uma sugestão, caso não conheçam este _style guide_ e/ou caso ainda não tenham nada definido.

**Comment by CleissonVieira** [comment]
Reunião com Andrew, Cleisson e Estela no dia 10/03/2021 sobre a enquete para definições de projeto:

- Front-end react e back-end node com graphql e apolo;
- Será feito uma página única composta por: menu de pastas de digitação, parte de preview e parte com estrutura de pastas para mostrar enquetes já criadas;
- Banco de dados dividido em duas tabelas: perguntas e respostas;
- Interpretador de texto para transformar em perguntas será implementado no front-end para oferecer preview ao usuário e eliminar a necessidade de realizar requisições ao back-end;
- Os dados, após passar pelo interpretador, serão enviados já transformados na enquete para o back/banco, assim quando o usuário final acessar a enquete não será necessário a reinterpretação da mesma. Dessa forma é possível realizar alterações futuras sem afetar dados já existentes;
- A enquete será livre para qualquer usuário acessar e responder, tendo acesso ao Qr-code ou link, sem a necessidade de login no sistema;
- Será utilizado método de status para as enquetes: rascunho (editável e não disponível para o publico), publicado (não editável, concluído e disponível para publico) e desabilitado (não disponível para publico, disponível em histórico de enquetes);
- Respostas dos usuários: a partir do momento que preencheu e enviou não é mais possível editar;
- Interpretador (quem transforma texto em perguntas): múltipla escolha -> [] , uma única escolha -> (), texto -> alfabeto, apenas números -> 0:9 , data -> 00/00/00 e hora 00:00;

**Comment by andrewmsilva** [comment]
Conforme acordado na última reunião, apenas algumas alterações no BD foram feitas, mas a base do projeto continua a mesma.
