### ISSUE TITLE
Criar diagrama ER e protótipos de tela

### ISSUE THREAD

**Issue by andrewmsilva** [practice-uffs/practice-enquete#12]
É necessário definir melhor os requisitos deste projeto para que ele possa ser devidamente desenvolvido. O primeiro passo é, após o fechamento da issue #1, criar o diagrama ER do banco de dados e prototipar todas as telas que serão criadas.

**Comment by CleissonVieira** [comment]
Para está tarefa foi criado duas novas Issues:

- Protótipo e dar inicio ao front-end: #13 
- Diagrama ER, criação de banco de dados e inicio ao back-end: #14

Com essa divisão acredito que por fins de organização está Issue pode ser fechada.
