### ISSUE TITLE
Criar diagrama ER e BD para dar inicio ao back-end

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/practice-enquete#14]
A partir dos dados da reunião do dia 10/03/2021 informados na #1 dar continuidade para criar o banco de dados e iniciar o trabalho no back-end:

- [x] Conforme #12 criar o diagrama ER com base em duas tabelas sendo Perguntas e Respostas;
- [x] Após confirmação de diagrama ER consistente com um bom fluxo, então dar inicio ao banco de dados criando de fato as tabelas;

**Comment by andrewmsilva** [comment]
Foi criada uma versão inicial do diagrama ER, o qual pode ser encontrado [aqui](https://drive.google.com/drive/folders/1ZMT1yJt7dgv5nqQw93o_vKvnaw5BkMtb). Peço feedback quanto a isso, @Dovyski e @CleissonVieira.

O `status` de um `Survey` e o `type` de uma `Question` foram definidos como `varchar` para eliminar tabelas intermediárias que conteriam apenas dados estáticos e evitar valores difíceis de serem interpretados, como um `status = 1`. Tendo um enum que diz que `status = "draft"`, por exemplo, facilita muito na hora de desenvolver funcionalidades.

**Comment by andrewmsilva** [comment]
Já foram criadas as entidades que compõem o banco de dados, conforme descrito no PR #15. No entanto, preciso que todos estejam de acordo com ER proposto antes de efetivar esta etapa. Qualquer sugestão, se bem explicada e pontuada, é bem vinda. Quaisquer alterações serão aplicadas tanto no ER como no PR #15, então peço para que não deem merge nele antes que tudo esteja pronto 😄

**Comment by Dovyski** [comment]
Eu tenho várias sugestões para fazer sobre o ER proposto, mas acho que será mais proveitoso fazermos isso em uma reunião. De qualquer forma, vou adiantar a análise aqui. O ER atual tem uma modelagem muito semelhante ao Google Forms, eu imagino. Eu acho isso muito válido, porém limitante em termos de dinamicidade de produção de conteúdo (que é o que queremos).

No meu entendimento, `Question` e `Survery` podem ser a mesma entidade. Nessa modelagem, `Survey` teria o texto completo que o usuário escreveu (vamos chamar de `content`), e um campo text `questions` que teria uma representação `json`, por exemplo, do conteúdo parseado a partir de `content`. Quando tivéssemos que mostrar um survey ao público, buscamos a tupla do `Survey` e renderizamos o form HTML com base no campo `questions`. Para cada resposta do usuário, uma tupla é colocado (ou atualizada) em `Answer`. Teriamos uma relação 1:1 entre `Survey` e `Answer`, muito mais fácil de gerenciar.

Meu segundo ponto é a entidade `Entry`. Eu acho que um nome melhor para ela seria `User`.

**Comment by CleissonVieira** [comment]
Eu acredito que uma reunião rápida via meet seja necessária para compreender o ER atual e a proposta feita pelo @Dovyski 
Através da primeira reunião feita com o @andrewmsilva e @estelavilasboas tinha entendido que `Question` e `Survery` seria uma única entidade, onde não seria salvo cada pergunta de forma separada, mas sim o questionário inteiro.

**Comment by andrewmsilva** [comment]
O ERD foi atualizado conforme o que foi definido em reunião.
